In [4]:
import mlp
import pandas
import sklearn

In [11]:
df = mlp.setup.extract().pipe(mlp.preprocessing.preprocess)

In [12]:
df

,temperature,feels_like_temperature,relative_humidity,windspeed,psi,weather_encoded,is_weekend,is_rush_hour,hr_y,hr_x,month_y,month_x,total_scooter
0,66.7,95.0,81.0,0.0,50,0,True,False,0.000000,1.000000,5.000000e-01,0.866025,97
1,65.0,93.2,80.0,0.0,6,0,True,False,0.258819,0.965926,5.000000e-01,0.866025,247
2,65.0,93.2,80.0,0.0,25,0,True,False,0.500000,0.866025,5.000000e-01,0.866025,202
3,66.7,95.0,75.0,0.0,41,0,True,False,0.707107,0.707107,5.000000e-01,0.866025,79
5,66.7,95.0,75.0,0.0,9,0,True,False,0.866025,0.500000,5.000000e-01,0.866025,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18636,68.4,91.4,60.0,11.0,15,1,False,False,-0.965926,0.258819,-2.449294e-16,1.000000,794
18637,68.4,91.4,60.0,11.0,25,1,False,False,-0.866025,0.500000,-2.449294e-16,1.000000,598
18638,68.4,91.4,60.0,11.0,35,0,False,False,-0.707107,0.707107,-2.449294e-16,1.000000,606
18640,68.4,93.2,56.0,9.0,8,0,False,False,-0.500000,0.866025,-2.449294e-16,1.000000,378
18641,68.4,93.2,65.0,9.0,49,0,False,False,-0.258819,0.965926,-2.449294e-16,1.000000,294